exclude: 'old/'
fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-merge-conflict
- repo: local
  hooks:
  - id: rustfmt
    name: rustfmt
    entry: rustfmt
    language: system
    always_run: true
    types: [rust]
    pass_filenames: false
