# vi:ft=toml:
#
# See more keys and their definitions at
#   https://doc.rust-lang.org/cargo/reference/manifest.html


[package]
name = "rust-door-knocker"
version = "UNKNOWN"
edition = "2021"
default-run = "knock"

[lib]
name = 'rlib'
path = 'src/lib.rs'
crate-type = ["lib"]
doctest = false

[[bin]]
name = "knock"
path = "src/knock.rs"

[[bin]]
name = "door"
path = "src/door.rs"

[dependencies]
exec = "0.3.1"
data-encoding = "2.3.2"
clap = { version = "3.2.8", features = [ "cargo" ] }
syslog = "^6.0"
log = { version = "0.4.17", features = [ "std" ] }
env_logger = "0.8.4"
strfmt = "0.2.2"
sha2 = "0.10"
tokio = { version="1.20.1", features=["full"] }
rand = "0.8.5"
lru = "0.7.8"
