
---
name: build

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    name: build
    runs-on: ubuntu-latest
    container: jettero/kersplat:1.0.28

    env:
      GITHUB_TOKEN: ${{ github.token }}
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'workaround for https://github.com/actions/checkout/issues/760'
        run: 'git config --global --add safe.directory ${GITHUB_WORKSPACE}'

      - run: make Cargo.toml

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          use-cross: yes
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - uses: actions/upload-artifact@v3
        with:
          name: door.x86_64-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/door

      - uses: actions/upload-artifact@v3
        with:
          name: knock.x86_64-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/knock
