
---
name: build

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:

  test:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-latest
    container: jettero/kersplat:1.0.28

    env:
      GITHUB_TOKEN: ${{ github.token }}

    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            name: x86_64-linux-gnu

          # apple-darwin builds just aren't going to work without some prety
          # major changes to kersplat or possibly using some other base image.

          # - target: x86_64-apple-darwin
          #   name: x86_64-apple-darwin

          # - target: aarch64-apple-darwin
          #   name: aarch64-apple-darwin

    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('input.toml') }}
          path:
            ~/.cargo
            target
          restore-keys:
            ${{ runner.os }}-

      - name: 'workaround for https://github.com/actions/checkout/issues/760'
        run: 'git config --global --add safe.directory ${GITHUB_WORKSPACE}'

      - run: make Cargo.toml

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          use-cross: yes
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - run: mv target/${{ matrix.platform.target }}/release/door door.${{ matrix.platform.name }}
      - run: mv target/${{ matrix.platform.target }}/release/knock knock.${{ matrix.platform.name }}

      - uses: actions/upload-artifact@v3
        with:
          name: door.${{ matrix.platform }}
          path: door.${{ matrix.platform }}

      - uses: actions/upload-artifact@v3
        with:
          name: knock.${{ matrix.platform }}
          path: knock.${{ matrix.platform }}
