
---
name: binaries

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:
  build_and_test:
    name: rust-door-knocker
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          use-cross: yes
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - run: find target -type f -name knock
      - run: find target -type f -name door

      - uses: actions/upload-artifact@v3
        with:
          name: door.x86_64-linux-gnu
          path: target/release/door

      - uses: actions/upload-artifact@v3
        with:
          name: knock.x86_64-linux-gnu
          path: target/release/knock
