
---
name: test

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('input.toml') }}
          path:
            ~/.cargo
            target
          restore-keys:
            ${{ runner.os }}-

      - run: make Cargo.toml

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test
